'use strict';
const $ = (selector, parent = document) => parent.querySelector(selector);
const titles = {dashboard:'Обзор',pages:'Тексты и страницы',products:'Товары',media:'Изображения и PDF',settings:'Контакты и настройки',mail:'Отправка писем',leads:'Заявки',backups:'Резервные копии',security:'Безопасность'};
const pageTitles = {index:'Главная',hidromak:'Каталог HIDRO-MAK',katmerciler:'Каталог KATMERCILER',catalog:'Весь каталог',product:'Карточка товара'};
const sectionTitles = {catalog:'Каталог',about:'О компании',request:'Форма заявки',services:'Услуги',certificates:'Сертификаты',contacts:'Контакты',description:'Описание',specifications:'Характеристики',selection:'Подбор'};
let csrf = '', state = null, dirty = false, editVersion = 0, currentView = 'dashboard', selectedPage = 'index', productId = null, setup = false, pickerCallback = null;
const activation = new URLSearchParams(location.hash.replace(/^#/, '')).get('setup') || '';
if (activation) history.replaceState(null, '', location.pathname);

function node(tag, text, attributes = {}) {
  const item = document.createElement(tag);
  if (text !== null && text !== undefined) item.textContent = text;
  Object.entries(attributes).forEach(([key, value]) => item.setAttribute(key, value));
  return item;
}
function button(text, action, className='secondary') { const b=node('button',text,{type:'button',class:className}); b.addEventListener('click',action);return b; }
function notice(message, error=false) { const n=$('#notice');n.textContent=message;n.className=error?'notice error':'notice';n.hidden=false; }
function markDirty() { dirty=true;editVersion++;$('#dirty-status').textContent='Есть несохранённые изменения'; }
function labelInput(title, value, callback, type='text', help='') {
  const label=node('label',title); const input=node(type==='textarea'?'textarea':'input',null,type==='textarea'?{}:{type});
  input.value=value??'';input.addEventListener('input',()=>{callback(input.value);markDirty();});label.append(input);
  if (help) label.append(node('span',help,{class:'hint'}));return label;
}
function checkbox(title, value, callback) { const label=node('label',null,{class:'check'});const input=node('input',null,{type:'checkbox'});input.checked=Boolean(value);input.addEventListener('change',()=>{callback(input.checked);markDirty();});label.append(input,node('span',title));return label; }
function panel(title, help='') { const p=node('section',null,{class:'panel'});if(title)p.append(node('h2',title));if(help)p.append(node('p',help,{class:'hint'}));return p; }
async function api(action, data=null, file=null) {
  const options={credentials:'same-origin',headers:{}};
  if(data!==null||file){options.method='POST';options.headers['X-CSRF-Token']=csrf;if(file){const form=new FormData();form.append('file',file);options.body=form;}else{options.headers['Content-Type']='application/json';options.body=JSON.stringify(data);}}
  const response=await fetch(`../api/admin.php?action=${encodeURIComponent(action)}`,options);
  let result;try { result=await response.json(); }catch{throw new Error('Сервер вернул некорректный ответ. Проверьте соединение.');}
  if(!response.ok){if(response.status===401&&state){state=null;await start();}throw new Error(result.error||'Не удалось выполнить действие.');}
  return result;
}
async function confirmed(title,message) {
  const dialog=$('#confirm-dialog');$('#confirm-title').textContent=title;$('#confirm-message').textContent=message;dialog.showModal();
  return new Promise(resolve=>{const finish=value=>{dialog.close();$('#confirm-ok').onclick=null;$('#confirm-cancel').onclick=null;resolve(value);};$('#confirm-ok').onclick=()=>finish(true);$('#confirm-cancel').onclick=()=>finish(false);dialog.oncancel=event=>{event.preventDefault();finish(false);};});
}
async function save() {
  const b=$('#save');b.disabled=true;
  const savingVersion=editVersion;
  try{const result=await api('save',{revision:state.content.revision,content:state.content});if(editVersion===savingVersion){state.content=result.content;dirty=false;$('#dirty-status').textContent='Все изменения сохранены';}else{state.content.revision=result.content.revision;state.content.updatedAt=result.content.updatedAt;}notice('Сайт обновлён. Предыдущая версия сохранена в резервной копии.');}
  catch(error){notice(error.message,true);}finally{b.disabled=false;}
}
async function load() { state=await api('state');dirty=false;$('#dirty-status').textContent='Все изменения сохранены';$('#signed-user').textContent=`Вход: ${state.username}`; }
async function navigate(view) { currentView=view;productId=null;$('#notice').hidden=true;$('#view-title').textContent=titles[view];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));await render(); }
async function render() {
  const view=$('#view');view.replaceChildren();
  try{await ({dashboard:dashboardView,pages:pagesView,products:productsView,media:mediaView,settings:settingsView,mail:mailView,leads:leadsView,backups:backupsView,security:securityView})[currentView](view);}catch(error){notice(error.message,true);}
}
function dashboardView(view) {
  const products=Object.values(state.content.products);const stats=node('div',null,{class:'stats'});
  [['Товаров в каталоге',products.length],['Опубликовано',products.filter(p=>p.published).length],['Редактируемых страниц',Object.keys(state.schema).length]].forEach(([title,count])=>{const item=node('div',null,{class:'stat'});item.append(node('strong',String(count)),node('span',title));stats.append(item);});view.append(stats);
  const p=panel('Сайт под вашим управлением','Изменения появляются на рабочем сайте после нажатия «Сохранить на сайт». GitHub Pages — отдельная статическая демонстрация.');
  p.append(node('p','Редактируйте тексты и изображения страниц, управляйте товарами и проверяйте входящие заявки. Перед каждым сохранением создаётся резервная копия.'));
  const row=node('div',null,{class:'row'});row.append(button('Редактировать товары',()=>navigate('products'),'primary'),button('Изменить контакты',()=>navigate('settings')),button('Посмотреть заявки',()=>navigate('leads')));p.append(row);view.append(p);
  if(!state.content.settings.mailEnabled)view.append(node('p','Почтовые уведомления выключены. Заявки сохраняются в разделе «Заявки». Настройте получателя и отправителя, затем проверьте отправку письма.',{class:'warning'}));
  if(!state.content.settings.indexingEnabled)view.append(node('p','Индексация рабочего сайта пока закрыта. Метрика и подтверждение Вебмастера настраиваются в разделе «Контакты и настройки». Демоверсия GitHub всегда закрыта от индексации.',{class:'warning'}));
}
function pagesView(view) {
  const filters=node('div',null,{class:'filters'});const choose=node('label','Страница');const select=node('select');Object.entries(pageTitles).forEach(([id,title])=>{const option=node('option',title,{value:id});option.selected=id===selectedPage;select.append(option);});choose.append(select);
  const searchLabel=node('label','Поиск текста или поля',{class:'search'});const search=node('input',null,{type:'search',placeholder:'Например: сертификат, ремонт, заголовок'});searchLabel.append(search);filters.append(choose,searchLabel);view.append(filters);
  const intro=node('p','Контакты и название в меню изменяются в настройках. Фотографии, характеристики и описание товара — в разделе «Товары». Обычные тексты вводите без HTML.',{class:'hint'});view.append(intro);
  const container=panel('');view.append(container);
  function showFields(){container.replaceChildren();const groups=new Map();const query=search.value.toLowerCase();Object.entries(state.schema[selectedPage]).forEach(([key,field])=>{const value=state.content.pages[selectedPage][key];if(query&&!`${field.label} ${value}`.toLowerCase().includes(query))return;if(!groups.has(field.section))groups.set(field.section,[]);groups.get(field.section).push([key,field]);});
    groups.forEach((fields,title)=>{const details=node('details');details.open=Boolean(query);details.append(node('summary',`${sectionTitles[title]||title} · ${fields.length} полей`));fields.forEach(([key,field])=>{const item=node('div',null,{class:'edit-field'});const value=state.content.pages[selectedPage][key];item.append(labelInput(field.label,value,value=>state.content.pages[selectedPage][key]=value,field.type==='text'&&value.length>140?'textarea':'text'));
      if(field.type==='image'){const preview=node('img',null,{src:'../'+value,alt:'Превью',class:'image-field-preview'});item.prepend(preview);item.append(button('Выбрать изображение',()=>pickMedia('image',path=>{state.content.pages[selectedPage][key]=path;markDirty();showFields();}),'secondary small'));}
      else if(field.type==='link'&&/\.pdf$/.test(value))item.append(button('Выбрать PDF',()=>pickMedia('pdf',path=>{state.content.pages[selectedPage][key]=path;markDirty();showFields();}),'secondary small'));
      details.append(item);});container.append(details);});if(!groups.size)container.append(node('p','Поля не найдены.',{class:'empty'}));
  }
  select.addEventListener('change',()=>{selectedPage=select.value;showFields();});search.addEventListener('input',showFields);showFields();
}
function productsView(view) {
  if(productId!==null){productEditor(view);return;}
  const top=node('div',null,{class:'row spread'});top.append(node('p','Сначала отредактируйте карточку, затем сохраните изменения на сайт.',{class:'hint'}),button('＋ Добавить товар',()=>{
    const id=`part-${Date.now().toString(36)}`;state.content.products[id]={title:'Новая запчасть',brand:'KATMERCILER',category:'',sku:'',summary:'',description:[''],specs:[],selection:'',price:'По запросу',availability:'Уточняйте наличие',photoNote:'',published:false,diagram:false,order:Object.keys(state.content.products).length,photos:[]};productId=id;markDirty();render();
  },'primary'));view.append(top);
  const filters=node('div',null,{class:'filters'});const searchLabel=node('label','Поиск товара',{class:'search'});const search=node('input',null,{type:'search',placeholder:'Название, марка или артикул'});searchLabel.append(search);filters.append(searchLabel);view.append(filters);
  const wrap=node('div',null,{class:'table-wrap'});const table=node('table');const head=node('thead');const tr=node('tr');['Фото','Товар','Цена и наличие','Статус',''].forEach(t=>tr.append(node('th',t)));head.append(tr);table.append(head);const body=node('tbody');table.append(body);wrap.append(table);view.append(wrap);
  function list(){body.replaceChildren();const query=search.value.toLowerCase();Object.entries(state.content.products).sort((a,b)=>a[1].order-b[1].order).filter(([,p])=>`${p.title} ${p.brand} ${p.sku}`.toLowerCase().includes(query)).forEach(([id,p])=>{const row=node('tr');const image=node('td');image.append(p.photos.length?node('img',null,{src:'../'+p.photos[0].src,alt:'',class:'table-photo'}):node('span','Нет фото',{class:'hint'}));const title=node('td');title.append(node('strong',p.title),node('span',`${p.brand} · ${p.sku||'без артикула'}`,{class:'hint'}));const price=node('td');price.append(node('strong',p.price),node('span',p.availability));const status=node('td');status.append(node('span',p.published?'Опубликован':'Черновик',{class:p.published?'badge':'badge draft'}));const actions=node('td');actions.append(button('Редактировать',()=>{productId=id;render();},'secondary small'));row.append(image,title,price,status,actions);body.append(row);});}search.addEventListener('input',list);list();
}
function productEditor(view) {
  const p=state.content.products[productId];const top=node('div',null,{class:'editor-top'});top.append(button('← К списку товаров',()=>{productId=null;render();}));const actions=node('div',null,{class:'inline-actions'});const link=node('a','Открыть карточку ↗',{href:`../product.html?part=${encodeURIComponent(productId)}`,target:'_blank',rel:'noopener'});actions.append(link,button('Дублировать',()=>{const id=`${productId.slice(0,50)}-copy-${Date.now().toString(36)}`;state.content.products[id]=structuredClone(p);state.content.products[id].title+=' — копия';state.content.products[id].published=false;productId=id;markDirty();render();}),button('Удалить товар',async()=>{if(await confirmed('Удалить товар?',`«${p.title}» исчезнет после сохранения. Предыдущая версия останется в резервной копии.`)){delete state.content.products[productId];productId=null;markDirty();render();}},'danger'));top.append(actions);view.append(top);
  const main=panel('Карточка запчасти');const slug=node('p',`Постоянный идентификатор: ${productId}`,{class:'hint'});main.append(slug);
  main.append(labelInput('Название',p.title,v=>p.title=v),checkbox('Опубликовать товар на сайте',p.published,v=>p.published=v));const grid=node('div',null,{class:'grid'});
  [['Марка техники','brand'],['Категория','category'],['Артикул','sku'],['Цена (например: 25 000 ₽ или «По запросу»)','price'],['Наличие','availability'],['Порядок в каталоге','order']].forEach(([label,key])=>grid.append(labelInput(label,p[key],v=>p[key]=key==='order'?Number(v):v,key==='order'?'number':'text')));main.append(grid,labelInput('Краткое описание',p.summary,v=>p.summary=v,'textarea'),labelInput('Полное описание (разделяйте абзацы пустой строкой)',p.description.join('\n\n'),v=>p.description=v.split(/\n\s*\n/).map(t=>t.trim()),'textarea'),labelInput('Что нужно для подбора',p.selection,v=>p.selection=v,'textarea'));view.append(main);
  const specs=panel('Характеристики');const rows=node('div');specs.append(rows);p.specs.forEach((pair,index)=>{const row=node('div',null,{class:'spec-row'});const key=node('input',null,{placeholder:'Характеристика','aria-label':`Характеристика ${index+1}`});key.value=pair[0];const value=node('input',null,{placeholder:'Значение','aria-label':`Значение ${index+1}`});value.value=pair[1];key.oninput=()=>{pair[0]=key.value;markDirty();};value.oninput=()=>{pair[1]=value.value;markDirty();};row.append(key,value,button('×',()=>{p.specs.splice(index,1);markDirty();render();},'secondary small'));rows.append(row);});specs.append(button('＋ Добавить характеристику',()=>{p.specs.push(['','']);markDirty();render();}));view.append(specs);
  const photos=panel('Фотографии','Первое изображение — главное. Поддерживается до 20 снимков. Для нового товара выберите его настоящую фотографию.');photos.append(checkbox('Изображения являются каталожной схемой',p.diagram,v=>p.diagram=v),labelInput('Подпись к фотографиям',p.photoNote,v=>p.photoNote=v));
  p.photos.forEach((photo,index)=>{const row=node('div',null,{class:'photo-row'});row.append(node('img',null,{src:'../'+photo.src,alt:photo.alt}));const fields=node('div');fields.append(labelInput(`Фото ${index+1}: описание для доступности`,photo.alt,v=>photo.alt=v));const actions=node('div',null,{class:'inline-actions'});actions.append(button('Заменить',()=>pickMedia('image',path=>{photo.src=path;markDirty();render();}),'secondary small'));if(index>0)actions.append(button('Сделать главным',()=>{p.photos.splice(index,1);p.photos.unshift(photo);markDirty();render();},'secondary small'));fields.append(actions);row.append(fields,button('Удалить',()=>{if(p.photos.length===1){notice('У товара должно остаться хотя бы одно фото.',true);return;}p.photos.splice(index,1);markDirty();render();},'secondary small'));photos.append(row);});photos.append(button('＋ Добавить фото',()=>{if(p.photos.length>=20){notice('Не более 20 снимков.',true);return;}pickMedia('image',path=>{p.photos.push({src:path,alt:p.title});markDirty();render();});}));view.append(photos);
}
function mediaCard(file, select=null) { const card=node('article',null,{class:'media-card'});if(file.kind==='image')card.append(node('img',null,{src:'../'+file.path,alt:file.name,loading:'lazy'}));else card.append(node('div','PDF',{class:'pdf'}));card.append(node('p',file.name),node('p',`${Math.ceil(file.size/1024)} КБ`,{class:'hint'}));if(select)card.append(button('Выбрать',()=>select(file.path),'primary small'));else{const actions=node('div',null,{class:'inline-actions'});actions.append(node('a','Открыть',{href:'../'+file.path,target:'_blank',rel:'noopener'}));if(file.deletable)actions.append(button('Удалить',async()=>{if(dirty){notice('Сначала сохраните изменения контента.',true);return;}if(await confirmed('Удалить файл?', 'Неиспользуемый файл будет перемещён в приватный архив на сервере.')){try{state.media=(await api('delete-media',{path:file.path})).media;render();}catch(error){notice(error.message,true);}}},'secondary small'));card.append(actions);}return card; }
function mediaView(view) {
  const upload=node('div',null,{class:'upload-box'});const label=node('label','Загрузить изображения или PDF (до 10 МБ на файл)');const input=node('input',null,{type:'file',accept:'image/jpeg,image/png,image/webp,application/pdf',multiple:''});label.append(input);upload.append(label,node('p','JPG, PNG, WebP или PDF. Файлы загружаются сразу; затем выберите их в тексте или карточке товара.',{class:'hint'}));view.append(upload);input.addEventListener('change',async()=>{input.disabled=true;try{for(const file of input.files){const result=await api('upload',null,file);state.media=result.media;}notice('Файлы загружены в медиатеку.');render();}catch(error){notice(error.message,true);}finally{input.disabled=false;}});
  const grid=node('div',null,{class:'media-grid'});state.media.forEach(file=>grid.append(mediaCard(file)));view.append(grid);
}
function pickMedia(kind,callback) { pickerCallback=callback;const grid=$('#picker-grid');grid.replaceChildren();state.media.filter(file=>file.kind===kind).forEach(file=>grid.append(mediaCard(file,path=>{$('#media-picker').close();pickerCallback(path);})));if(!grid.children.length)grid.append(node('p','Сначала загрузите файл в раздел «Изображения и PDF».'));$('#media-picker').showModal(); }
function settingsView(view) {
  state.content.settings.labels ||= {details:'Подробнее',order:'Запросить цену',submit:'Отправить заявку',sku:'Артикул',brand:'Техника',skuMissing:'Артикул уточняется при подборе',photo:'Фото',diagram:'Каталожная схема',emptyCatalog:'В этом разделе пока нет опубликованных запчастей. Свяжитесь с нами для подбора.',liveFormNote:'Заявка сохранится у владельца сайта. Для срочного вопроса позвоните нам.'};
  const s=state.content.settings;const contacts=panel('Название и контакты','Эти данные обновляются на всех страницах сайта.');
  [['Название в меню','brand'],['Название компании / ИП','company'],['Телефон','phone'],['Публичная электронная почта','email'],['Адрес','address']].forEach(([title,key])=>contacts.append(labelInput(title,s[key],v=>s[key]=v,key==='email'?'email':'text')));view.append(contacts);
  const leads=panel('Заявки и сообщения');leads.append(labelInput('Почта, на которую отправлять заявки',s.recipient,v=>s.recipient=v,'email'),labelInput('Адрес отправителя письма',s.sender,v=>s.sender=v,'email','Не указывайте @mail.ru как отправителя через PHP mail. Для этого нужен SMTP с авторизацией.'),checkbox('Отправлять уведомления по электронной почте',s.mailEnabled,v=>s.mailEnabled=v),labelInput('Сообщение посетителю после сохранения заявки',s.leadSuccess,v=>s.leadSuccess=v,'textarea'),labelInput('Текст согласия на использование контактных данных',s.consentText,v=>s.consentText=v,'textarea'));view.append(leads);
  const codes=panel('Яндекс Метрика и Вебмастер','Коды устанавливаются на все страницы рабочего сайта. Демонстрация GitHub не отправляет данные в аналитику.');codes.append(labelInput('Код Яндекс Метрики или номер счётчика',s.metricaCode,v=>s.metricaCode=v,'textarea','Из стандартного кода извлекается номер счётчика; произвольный JavaScript не выполняется.'),checkbox('Включить Вебвизор в Метрике',s.webvisor,v=>s.webvisor=v),labelInput('Метатег Вебмастера или значение yandex-verification',s.webmasterCode,v=>s.webmasterCode=v,'textarea'),checkbox('Разрешить индексацию рабочего сайта (GitHub-демо остаётся закрытой)',s.indexingEnabled,v=>s.indexingEnabled=v));view.append(codes);
  const labelNames={details:'Кнопка подробностей',order:'Кнопка запроса цены',submit:'Кнопка отправки заявки',sku:'Название поля артикула',brand:'Название поля марки техники',skuMissing:'Сообщение без артикула',photo:'Название фотографии',diagram:'Название каталожной схемы',emptyCatalog:'Пустой каталог',liveFormNote:'Подсказка под формой'};
  const labels=panel('Надписи каталога и формы');Object.entries(s.labels).forEach(([key,value])=>labels.append(labelInput(labelNames[key]||key,value,v=>s.labels[key]=v)));view.append(labels);
}
function mailView(view) {
  const mail=state.mail;const p=panel('Способ отправки уведомлений','Получатель и адрес отправителя задаются в «Контактах и настройках». SMTP-пароль хранится отдельно от исходников и не возвращается браузеру.');
  p.append(node('p',`Получатель: ${state.content.settings.recipient}. Отправитель: ${state.content.settings.sender}.`,{class:'hint'}));
  const form=node('form');const choose=node('label','Способ отправки');const mode=node('select',null,{name:'mode'});[['mail','PHP mail на хостинге'],['smtp','SMTP с авторизацией']].forEach(([value,text])=>{const o=node('option',text,{value});o.selected=mail.mode===value;mode.append(o);});choose.append(mode);form.append(choose);
  [['SMTP-сервер','host',mail.host,'text'],['Порт (465 или 587)','port',mail.port,'number'],['Логин почтового ящика','username',mail.username,'text'],['Пароль SMTP (пустое поле — оставить прежний)','password','','password']].forEach(([title,key,value,type])=>{const l=node('label',title);const i=node('input',null,{type,name:key,autocomplete:key==='password'?'new-password':'off'});i.value=value;l.append(i);form.append(l);});const securityLabel=node('label','Шифрование');const security=node('select',null,{name:'security'});[['ssl','SSL/TLS (обычно порт 465)'],['tls','STARTTLS (обычно порт 587)']].forEach(([value,text])=>{const option=node('option',text,{value});option.selected=mail.security===value;security.append(option);});securityLabel.append(security);form.append(securityLabel,node('p',mail.hasPassword?'Пароль SMTP уже сохранён.':'Пароль SMTP пока не задан.',{class:'hint'}));const submit=node('button','Сохранить параметры отправки',{type:'submit',class:'primary'});form.append(submit);form.addEventListener('submit',async event=>{event.preventDefault();submit.disabled=true;try{const input=Object.fromEntries(new FormData(form));input.port=Number(input.port);state.mail=(await api('save-mail',input)).mail;notice('Параметры почтового транспорта сохранены.');render();}catch(error){notice(error.message,true);}finally{submit.disabled=false;}});p.append(form);view.append(p);
  const test=panel('Проверка письма','Сначала сохраните получателя и отправителя на сайт. Успех означает, что почтовый сервер принял письмо, а не гарантированную доставку во «Входящие». Проверьте также «Спам».');test.append(button('Отправить тестовое письмо',async()=>{if(dirty){notice('Сначала сохраните изменения контента.',true);return;}if(!await confirmed('Отправить тестовое письмо?',`Одно письмо будет отправлено на ${state.content.settings.recipient}.`))return;try{const result=await api('test-mail',{});notice(result.status==='accepted'?'Письмо принято почтовым сервером. Проверьте ящик получателя и папку «Спам».':'Отправка не удалась. Проверьте SMTP-параметры или почту домена.',result.status!=='accepted');}catch(error){notice(error.message,true);}},'primary'));view.append(test);
}
async function leadsView(view) {
  const leads=(await api('leads')).leads;if(!leads.length){view.append(panel('Пока нет заявок','Новые заявки с сайта появятся здесь, даже если отправка уведомления по почте завершится ошибкой.'));return;}
  const statuses={new:'Новая',in_progress:'В работе',done:'Обработана',archived:'Архив'};const mailStatuses={pending:'Ожидает отправки',accepted:'Принято почтовым сервером (доставка не подтверждена)',failed:'Ошибка отправки',disabled:'Уведомления выключены'};
  leads.forEach(lead=>{const p=node('article',null,{class:'lead-card'});const head=node('div',null,{class:'row spread'});const title=node('div');title.append(node('h2',lead.name),node('p',`${new Date(lead.createdAt).toLocaleString('ru-RU')} · ${lead.id}`,{class:'lead-meta'}));const select=node('select',null,{'aria-label':`Статус заявки ${lead.id}`});Object.entries(statuses).forEach(([value,label])=>{const o=node('option',label,{value});o.selected=lead.status===value;select.append(o);});select.addEventListener('change',async()=>{try{await api('update-lead',{id:lead.id,status:select.value});notice('Статус заявки сохранён.');}catch(error){notice(error.message,true);}});head.append(title,select);const contact=node('div',null,{class:'lead-contact'});contact.append(node('a',lead.email,{href:'mailto:'+lead.email}));if(lead.phone)contact.append(node('span',lead.phone));p.append(head,contact,node('pre',lead.comment),node('p',`Уведомление: ${mailStatuses[lead.mailStatus]||lead.mailStatus}`,{class:'hint'}));view.append(p);});
}
async function backupsView(view) {
  const p=panel('Предыдущие версии','Хранятся последние 30 версий текстов, настроек и каталога. Восстановление тоже создаёт резервную копию. Заявки и пароли не входят в эти копии.');const download=node('a','Скачать текущий контент (JSON)',{href:'../api/admin.php?action=download'});p.append(download);const backups=(await api('backups')).backups;if(!backups.length)p.append(node('p','Копии появятся после первого сохранения.',{class:'hint'}));backups.forEach(backup=>{const row=node('div',null,{class:'backup-row'});row.append(node('span',new Date(backup.createdAt).toLocaleString('ru-RU')),button('Восстановить',async()=>{if(dirty){notice('Сначала сохраните изменения или обновите данные.',true);return;}if(await confirmed('Восстановить версию?',`Тексты, настройки и товары будут заменены версией от ${new Date(backup.createdAt).toLocaleString('ru-RU')}.`)){try{state.content=(await api('restore',{id:backup.id,revision:state.content.revision})).content;notice('Версия восстановлена.');render();}catch(error){notice(error.message,true);}}}));p.append(row);});view.append(p);
}
function securityView(view) {
  const p=panel('Сменить пароль','После смены пароля остальные сеансы будут отключены. Пароль не сохраняется в исходниках сайта.');const form=node('form');[['Текущий пароль','oldPassword','current-password'],['Новый пароль (от 12 символов)','password','new-password'],['Повтор нового пароля','confirm','new-password']].forEach(([title,key,autocomplete])=>{const label=node('label',title);label.append(node('input',null,{type:'password',name:key,required:'',autocomplete}));form.append(label);});form.append(node('button','Изменить пароль',{type:'submit',class:'primary'}));form.addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form));if(data.password!==data.confirm){notice('Новые пароли не совпадают.',true);return;}try{const result=await api('password',data);csrf=result.csrf;form.reset();notice('Пароль изменён. Другие сеансы отключены.');}catch(error){notice(error.message,true);}});p.append(form);view.append(p);
}
async function start() {
  try {const status=await api('status');csrf=status.csrf;if(status.authenticated){await load();$('#auth-screen').hidden=true;$('#app').hidden=false;await navigate('dashboard');return;}setup=status.setupAvailable;$('#app').hidden=true;$('#auth-screen').hidden=false;$('#setup-token-label').hidden=!setup;$('#password-help').hidden=!setup;$('#auth-title').textContent=setup?'Первый вход':'Вход в админку';$('#auth-submit').textContent=setup?'Создать доступ':'Войти';$('#auth-help').textContent=setup?'Используйте одноразовый код и задайте собственный логин и пароль.':'Изменения доступны только владельцу сайта.';$('#auth-form [name=token]').value=activation;$('#auth-form [name=password]').autocomplete=setup?'new-password':'current-password';}
  catch(error){$('#auth-screen').hidden=false;$('#auth-error').textContent=error.message;}
}
$('#auth-form').addEventListener('submit',async event=>{event.preventDefault();$('#auth-error').textContent='';$('#auth-submit').disabled=true;try{const result=await api(setup?'setup':'login',Object.fromEntries(new FormData(event.target)));csrf=result.csrf;event.target.reset();await start();}catch(error){$('#auth-error').textContent=error.message;}finally{$('#auth-submit').disabled=false;}});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.view)));
$('#save').addEventListener('click',save);
$('#reload').addEventListener('click',async()=>{if(dirty&&!await confirmed('Обновить данные?','Несохранённые изменения в этом окне будут потеряны.'))return;try{await load();productId=null;await render();notice('Данные обновлены.');}catch(error){notice(error.message,true);}});
$('#logout').addEventListener('click',async()=>{if(dirty&&!await confirmed('Выйти без сохранения?','Несохранённые изменения останутся только в этом окне и будут потеряны.'))return;try{await api('logout',{});dirty=false;state=null;await start();}catch(error){notice(error.message,true);}});
$('#picker-close').addEventListener('click',()=>$('#media-picker').close());
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
start();
